### ISSUE TITLE
QualityGateStatusExcludeList doesn't work

### ISSUE THREAD

**Issue by alexvaccaro** [highbyte/SonarqubeMSTeamsBridge#10]
Hi, first of all thanks for the code, I have found it very useful.

There is a small bug in `SonarqubeToMSTeamsFilter.cs` at line 21 instead of checking _data.qualityGate.status_ it should be checking for the value _data.status_.

Another small issue I have found is that the ps1 scripts requires the `--csharp` flag with the `functionapp publish` command

**Comment by alexvaccaro** [comment]
Actually, ignore my comment above about status, the _data.qualityGate.status_ is the right value to check, I got confused because the documentation has an example of how to exclude 'SUCCESS' but quality gate status return 'OK' when successful.

**Comment by highbyte** [comment]
No problem.

Regarding requiring a ```--csharp``` flag with the ```func azure functionapp publish```, I cannot seem to reproduce it with the .ps1 scripts. It works for me without it. I've tested with Azure Functions Core Tools v3.0.2630 and v3.0.3442 (latest).  Maybe it's required with other versions.
